### ISSUE TITLE
Tasks Proposals

### ISSUE THREAD

**Issue by icaromh** [icaromh/DollyFlix#13]

**Comment by icaromh** [comment]
@igorcmoura

**Comment by igorcmoura** [comment]
About improving files structure: [A Better File Structure For React/Redux Applications](https://marmelab.com/blog/2015/12/17/react-directory-structure.html)

**Comment by icaromh** [comment]
@igorcmoura You know what? We could talk with GloboPlay guys and see how they organize that :smiley:
