### ISSUE TITLE
Add Jest for tests

### ISSUE THREAD

**Issue by icaromh** [icaromh/DollyFlix#2]

**Comment by AyoAlfonso** [comment]
Can I handle this ? Is there a slack channel to get ideas on how to get started on the repo?

**Comment by igorcmoura** [comment]
@AyoAlfonso We're making this project to learn React, Jest and other technologies, so it's not totally open for contributions. Minor changes like bug fixes and documentation we may accept. But implementing new features we prefer to do it ourselves.
But of course, you can fork this project and use it as you want.
