### ISSUE TITLE
Request features

### ISSUE THREAD

**Issue by knkrth** [icaromh/dollyflix#44]
Add movie icon to add movies & On https://flix.icaromh.com/show/ncis-los-angeles/2 the preview image size are different (uneven) is there is a way to display all image preview in a same size?

**Comment by icaromh** [comment]
Hi @knkrth! 
Thanks for your report. I'll fix the thumbnails soon. 

The main goal of Dollyflix it's to provide shows without ads. So, if you know any site that has the movie in `.mp4` format without ads I can add to the crawler and add it to Dollyflix.

**Comment by knkrth** [comment]
@icaromh There are some ads on http://www2.putlockertv.ist but you can scrap embed video.

**Comment by knkrth** [comment]
Does this has admin page to manage & upload tv shows? Provide a movie section to upload movies.

**Comment by icaromh** [comment]
@knkrth Sorry the delay. I fixed the posters size.

No, It doesn't have any admin panel. The API it's populated through a web crawler I'd made. 

For now, I don't have the intention to implement an admin panel. Maybe a collection to fix some wrong slugs from the crawler to find information in the IMDB API.

**Comment by knkrth** [comment]
Keep up the good work :) 👍
